[build]
  command = "cd netlify/functions && npm install && npx prisma generate --schema=../prisma/schema.prisma && cd .. && npm run build"
  publish = "dist"
  functions = "netlify/functions"

[build.environment]
  NODE_VERSION = "20"
  PRISMA_CLI_QUERY_ENGINE_TYPE = "library"

[[redirects]]
  from = "/api/*"
  to = "/.netlify/functions/:splat"
  status = 200

[[redirects]]
  from = "/*"
  to = "/index.html"
  status = 200
